module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary:              '#DD3202',
        'primary-container':  '#B12500',
        'primary-dim':        '#8B1B00',
        'inverse-primary':    '#FFB4A3',
        secondary:            '#2F3131',
        'secondary-container':'#444650',
        tertiary:             '#5F5C4E',
        'tertiary-container': '#F8F4EA',
        charcoal:             '#1C1C1C',
        surface:              '#F9F9F9',
        'surface-warm':       '#F8F4EA',
        'surface-lowest':     '#FFFFFF',
        'surface-low':        '#F3F3F4',
        'surface-mid':        '#EEEEEE',
        'surface-high':       '#E8E8E8',
        'on-surface':         '#1C1C1C',
        'on-surface-variant': '#5C4039',
        'inverse-surface':    '#2F3131',
        'inverse-on-surface': '#F0F1F1',
        outline:              '#916F67',
        'outline-variant':    '#E6BDB4',
        'border-neutral':     '#E5E7EB',
        muted:                '#6D6A63',
        'accent-lime':        '#D9FD3B',
        error:                '#D64545',
      },
      fontFamily: {
        headline: ["'Space Grotesk'", 'sans-serif'],
        body:     ["'Wix Madefor Text'", 'sans-serif'],
        sans:     ["'Wix Madefor Text'", 'sans-serif'],
      },
      borderRadius: {
        none:    '0px',
        sm:      '2px',
        DEFAULT: '4px',
        md:      '6px',
        lg:      '8px',
        xl:      '12px',
        full:    '9999px',
      },
      letterSpacing: {
        tightest: '-0.04em',
        tighter:  '-0.03em',
        tight:    '-0.02em',
        label:    '0.06em',
        'label-sm': '0.08em',
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            hr: {
              borderColor: theme('colors.border-neutral'),
              borderTopWidth: '1px',
              marginTop: '2rem',
              marginBottom: '2rem',
            },
            'ol > li::before': { color: theme('colors.charcoal') },
            'ul > li::before': { backgroundColor: theme('colors.charcoal') },
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
